<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OnboardingPresetSeeder extends Seeder
{
    public function run(): void
    {
        $presets = $this->presets();

        foreach ($presets as $preset) {
            DB::table('onboarding_presets')->updateOrInsert(
                ['industry_key' => $preset['industry_key']],
                array_merge($preset, ['created_at' => now(), 'updated_at' => now()])
            );
        }
    }

    private function presets(): array
    {
        return [
            [
                'industry_key' => 'retail_ecommerce',
                'industry_name' => 'Retail & E-commerce',
                'icon_emoji' => '🛍️',
                'description' => 'Physical stores, online shops, and omnichannel retail operations.',
                'color_theme' => '#f59e0b',
                'recommended_modules' => ['inventory', 'sales', 'finance', 'procurement', 'hr', 'marketing', 'contracts'],
                'departments_template' => [
                    ['name' => 'Sales & Customer Service', 'code' => 'SALES'],
                    ['name' => 'Warehouse & Fulfillment', 'code' => 'WHOUSE'],
                    ['name' => 'Marketing', 'code' => 'MKT'],
                    ['name' => 'Finance & Accounting', 'code' => 'FIN'],
                    ['name' => 'IT & Systems', 'code' => 'IT'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash and Cash Equivalents', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Inventory', 'type' => 'asset'],
                    ['code' => '1300', 'name' => 'Prepaid Expenses', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Property & Equipment', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Credit Card Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Product Sales Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Shipping Revenue', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Returns & Refunds', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Cost of Goods Sold', 'type' => 'expense'],
                    ['code' => '5100', 'name' => 'Shipping & Fulfillment Costs', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Wages & Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Rent & Occupancy', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Marketing & Advertising', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Software & Technology', 'type' => 'expense'],
                    ['code' => '6400', 'name' => 'Payment Processing Fees', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'manufacturing',
                'industry_name' => 'Manufacturing & Production',
                'icon_emoji' => '🏭',
                'description' => 'Factories, workshops, and production operations.',
                'color_theme' => '#6366f1',
                'recommended_modules' => ['manufacturing', 'inventory', 'procurement', 'quality', 'assets', 'hr', 'finance'],
                'departments_template' => [
                    ['name' => 'Production', 'code' => 'PROD'],
                    ['name' => 'Quality Control', 'code' => 'QC'],
                    ['name' => 'Procurement & Supply Chain', 'code' => 'PROC'],
                    ['name' => 'Maintenance & Engineering', 'code' => 'MAINT'],
                    ['name' => 'Finance & Accounting', 'code' => 'FIN'],
                    ['name' => 'Human Resources', 'code' => 'HR'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Raw Materials Inventory', 'type' => 'asset'],
                    ['code' => '1210', 'name' => 'WIP Inventory', 'type' => 'asset'],
                    ['code' => '1220', 'name' => 'Finished Goods Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Plant & Equipment', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Shareholders Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Product Revenue', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Direct Materials', 'type' => 'expense'],
                    ['code' => '5100', 'name' => 'Direct Labour', 'type' => 'expense'],
                    ['code' => '5200', 'name' => 'Manufacturing Overhead', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Salaries & Wages', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Depreciation', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Maintenance & Repairs', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Utilities', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'construction_real_estate',
                'industry_name' => 'Construction & Real Estate',
                'icon_emoji' => '🏗️',
                'description' => 'Builders, developers, contractors, and property management.',
                'color_theme' => '#f97316',
                'recommended_modules' => ['projects', 'contracts', 'assets', 'hr', 'procurement', 'finance', 'documents'],
                'departments_template' => [
                    ['name' => 'Project Management', 'code' => 'PM'],
                    ['name' => 'Site Operations', 'code' => 'SITE'],
                    ['name' => 'Estimating & Contracts', 'code' => 'EST'],
                    ['name' => 'Finance & Accounting', 'code' => 'FIN'],
                    ['name' => 'Safety & Compliance', 'code' => 'SAFETY'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Construction Materials Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Equipment & Plant', 'type' => 'asset'],
                    ['code' => '1600', 'name' => 'Properties Under Development', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Retention Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Construction Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Property Sales Revenue', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Direct Construction Costs', 'type' => 'expense'],
                    ['code' => '5100', 'name' => 'Subcontractor Costs', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Wages & Labour', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Equipment Hire', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Site Costs', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'healthcare_medical',
                'industry_name' => 'Healthcare & Medical',
                'icon_emoji' => '🏥',
                'description' => 'Clinics, hospitals, medical practices, and allied health.',
                'color_theme' => '#10b981',
                'recommended_modules' => ['hr', 'quality', 'assets', 'documents', 'finance', 'inventory', 'field_service'],
                'departments_template' => [
                    ['name' => 'Clinical Operations', 'code' => 'CLIN'],
                    ['name' => 'Administration', 'code' => 'ADMIN'],
                    ['name' => 'Nursing & Allied Health', 'code' => 'NURSE'],
                    ['name' => 'Finance & Billing', 'code' => 'FIN'],
                    ['name' => 'Quality & Compliance', 'code' => 'QC'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Medical Supplies Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Medical Equipment', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Patient Service Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Government Funding', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Medical Supplies Expense', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Clinical Staff Wages', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Administrative Wages', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Equipment Maintenance', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Insurance & Compliance', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'professional_services',
                'industry_name' => 'Professional Services',
                'icon_emoji' => '💼',
                'description' => 'Consulting, legal, accounting, and advisory firms.',
                'color_theme' => '#8b5cf6',
                'recommended_modules' => ['projects', 'expenses', 'contracts', 'hr', 'sales', 'finance', 'documents', 'lms'],
                'departments_template' => [
                    ['name' => 'Consulting', 'code' => 'CONSULT'],
                    ['name' => 'Business Development', 'code' => 'BD'],
                    ['name' => 'Finance & Administration', 'code' => 'FIN'],
                    ['name' => 'Human Resources', 'code' => 'HR'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Unbilled Work in Progress', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Deferred Revenue', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Partner Capital', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Consulting Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Retainer Revenue', 'type' => 'revenue'],
                    ['code' => '6000', 'name' => 'Professional Staff Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Travel & Entertainment', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Professional Development', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Software & Tools', 'type' => 'expense'],
                    ['code' => '6400', 'name' => 'Office & Administration', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'hospitality_food',
                'industry_name' => 'Hospitality & Food Service',
                'icon_emoji' => '🍽️',
                'description' => 'Restaurants, cafes, hotels, bars, and catering.',
                'color_theme' => '#ef4444',
                'recommended_modules' => ['inventory', 'hr', 'sales', 'finance', 'assets', 'procurement'],
                'departments_template' => [
                    ['name' => 'Front of House', 'code' => 'FOH'],
                    ['name' => 'Kitchen', 'code' => 'KITCHEN'],
                    ['name' => 'Bar & Beverages', 'code' => 'BAR'],
                    ['name' => 'Events & Functions', 'code' => 'EVENTS'],
                    ['name' => 'Finance & Administration', 'code' => 'FIN'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash & POS', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Food & Beverage Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Kitchen Equipment', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Food Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Beverage Revenue', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Events & Functions Revenue', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Cost of Food Sold', 'type' => 'expense'],
                    ['code' => '5100', 'name' => 'Cost of Beverages Sold', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Wages & Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Rent & Occupancy', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Utilities', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'technology_software',
                'industry_name' => 'Technology & Software',
                'icon_emoji' => '💻',
                'description' => 'SaaS companies, software agencies, IT firms, and tech startups.',
                'color_theme' => '#3b82f6',
                'recommended_modules' => ['projects', 'sales', 'lms', 'hr', 'finance', 'contracts', 'expenses', 'field_service'],
                'departments_template' => [
                    ['name' => 'Engineering', 'code' => 'ENG'],
                    ['name' => 'Product', 'code' => 'PRODUCT'],
                    ['name' => 'Sales & Marketing', 'code' => 'SALES'],
                    ['name' => 'Customer Success', 'code' => 'CS'],
                    ['name' => 'Finance & Operations', 'code' => 'FIN'],
                    ['name' => 'Human Resources', 'code' => 'HR'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Deferred Tax Asset', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Deferred Revenue', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Share Capital', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Software Subscription Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Professional Services Revenue', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Support & Maintenance Revenue', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Cloud Infrastructure Costs', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Engineering Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Sales & Marketing Salaries', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'SaaS & Software Tools', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'R&D Expenses', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'wholesale_distribution',
                'industry_name' => 'Wholesale & Distribution',
                'icon_emoji' => '📦',
                'description' => 'Wholesalers, distributors, and supply chain businesses.',
                'color_theme' => '#0891b2',
                'recommended_modules' => ['inventory', 'procurement', 'sales', 'assets', 'hr', 'finance', 'contracts'],
                'departments_template' => [
                    ['name' => 'Warehouse & Logistics', 'code' => 'WHOUSE'],
                    ['name' => 'Sales', 'code' => 'SALES'],
                    ['name' => 'Procurement', 'code' => 'PROC'],
                    ['name' => 'Finance & Accounting', 'code' => 'FIN'],
                    ['name' => 'IT & Systems', 'code' => 'IT'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Warehouse & Equipment', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Sales Revenue', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Cost of Goods Sold', 'type' => 'expense'],
                    ['code' => '5100', 'name' => 'Freight & Logistics', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Wages & Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Warehouse Rent', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Fuel & Transport', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'agriculture',
                'industry_name' => 'Agriculture & Farming',
                'icon_emoji' => '🌾',
                'description' => 'Farms, orchards, vineyards, and agricultural businesses.',
                'color_theme' => '#65a30d',
                'recommended_modules' => ['inventory', 'assets', 'hr', 'procurement', 'finance', 'projects'],
                'departments_template' => [
                    ['name' => 'Farm Operations', 'code' => 'FARM'],
                    ['name' => 'Equipment & Maintenance', 'code' => 'EQUIP'],
                    ['name' => 'Sales & Marketing', 'code' => 'SALES'],
                    ['name' => 'Finance & Administration', 'code' => 'FIN'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Livestock & Crops Inventory', 'type' => 'asset'],
                    ['code' => '1300', 'name' => 'Farm Supplies Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Land & Property', 'type' => 'asset'],
                    ['code' => '1600', 'name' => 'Farm Equipment & Machinery', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Crop Sales', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Livestock Sales', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Subsidies & Grants', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Seeds & Fertilisers', 'type' => 'expense'],
                    ['code' => '5100', 'name' => 'Feed & Veterinary', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Wages & Seasonal Labour', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Fuel & Machinery', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Water & Irrigation', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'transportation_logistics',
                'industry_name' => 'Transportation & Logistics',
                'icon_emoji' => '🚛',
                'description' => 'Freight, courier, shipping, and logistics companies.',
                'color_theme' => '#78716c',
                'recommended_modules' => ['assets', 'field_service', 'hr', 'finance', 'procurement', 'sales', 'contracts'],
                'departments_template' => [
                    ['name' => 'Operations & Dispatch', 'code' => 'OPS'],
                    ['name' => 'Fleet Management', 'code' => 'FLEET'],
                    ['name' => 'Sales & Customer Service', 'code' => 'SALES'],
                    ['name' => 'Finance & Compliance', 'code' => 'FIN'],
                    ['name' => 'Safety & Compliance', 'code' => 'SAFETY'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Fleet Vehicles', 'type' => 'asset'],
                    ['code' => '1600', 'name' => 'Equipment & Trailers', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Vehicle Finance Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Freight Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Courier Revenue', 'type' => 'revenue'],
                    ['code' => '6000', 'name' => 'Driver Wages', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Fuel', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Vehicle Maintenance', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Insurance', 'type' => 'expense'],
                    ['code' => '6400', 'name' => 'Tolls & Registration', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'education_training',
                'industry_name' => 'Education & Training',
                'icon_emoji' => '🎓',
                'description' => 'Schools, training providers, tutoring centres, and EdTech.',
                'color_theme' => '#0ea5e9',
                'recommended_modules' => ['lms', 'hr', 'finance', 'documents', 'projects', 'assets'],
                'departments_template' => [
                    ['name' => 'Teaching & Instruction', 'code' => 'TEACH'],
                    ['name' => 'Student Services', 'code' => 'STUDENT'],
                    ['name' => 'Curriculum & Content', 'code' => 'CURR'],
                    ['name' => 'Finance & Administration', 'code' => 'FIN'],
                    ['name' => 'IT & Learning Systems', 'code' => 'IT'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Equipment & Technology', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Deferred Tuition Revenue', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Tuition & Course Fees', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Government Funding', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Corporate Training Revenue', 'type' => 'revenue'],
                    ['code' => '6000', 'name' => 'Staff Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Course Materials', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Facility & Rent', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Technology & Platforms', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'nonprofit',
                'industry_name' => 'Non-Profit & NGO',
                'icon_emoji' => '🤝',
                'description' => 'Charities, foundations, community organisations, and NGOs.',
                'color_theme' => '#d946ef',
                'recommended_modules' => ['projects', 'hr', 'finance', 'documents', 'lms', 'expenses'],
                'departments_template' => [
                    ['name' => 'Programs & Services', 'code' => 'PROG'],
                    ['name' => 'Fundraising & Development', 'code' => 'FUND'],
                    ['name' => 'Finance & Compliance', 'code' => 'FIN'],
                    ['name' => 'Communications', 'code' => 'COMMS'],
                    ['name' => 'Volunteer Management', 'code' => 'VOL'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Grants Receivable', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Deferred Grant Revenue', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Retained Surplus', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Donations & Gifts', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Government Grants', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Fundraising Revenue', 'type' => 'revenue'],
                    ['code' => '4300', 'name' => 'Program Fees', 'type' => 'revenue'],
                    ['code' => '6000', 'name' => 'Staff Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Program Expenses', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Fundraising Costs', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Administration', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'financial_services',
                'industry_name' => 'Financial Services',
                'icon_emoji' => '🏦',
                'description' => 'Accounting firms, financial advisors, insurance, and fintech.',
                'color_theme' => '#1d4ed8',
                'recommended_modules' => ['finance', 'sales', 'contracts', 'documents', 'hr', 'quality', 'expenses'],
                'departments_template' => [
                    ['name' => 'Client Services', 'code' => 'CLIENT'],
                    ['name' => 'Advisory & Planning', 'code' => 'ADVISORY'],
                    ['name' => 'Compliance & Risk', 'code' => 'COMPLIANCE'],
                    ['name' => 'Finance & Operations', 'code' => 'FIN'],
                    ['name' => 'IT & Security', 'code' => 'IT'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash & Client Trust Accounts', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Investments', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Client Funds Held', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Fee Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Commission Revenue', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Interest Income', 'type' => 'revenue'],
                    ['code' => '6000', 'name' => 'Professional Staff Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Compliance & Licensing', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Professional Indemnity Insurance', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Technology & Systems', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'media_creative',
                'industry_name' => 'Media & Creative Agency',
                'icon_emoji' => '🎨',
                'description' => 'Creative agencies, media production, design studios, and publishers.',
                'color_theme' => '#ec4899',
                'recommended_modules' => ['projects', 'assets', 'sales', 'expenses', 'contracts', 'finance', 'hr', 'lms'],
                'departments_template' => [
                    ['name' => 'Creative & Design', 'code' => 'CREATIVE'],
                    ['name' => 'Production', 'code' => 'PROD'],
                    ['name' => 'Client Services & Sales', 'code' => 'CLIENT'],
                    ['name' => 'Finance & Operations', 'code' => 'FIN'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Equipment & Studio Assets', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '2200', 'name' => 'Deferred Project Revenue', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Project Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Retainer Revenue', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Licensing & Royalties', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Contractor & Freelancer Costs', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Creative Staff Salaries', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Software & Creative Tools', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Production Costs', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Business Development', 'type' => 'expense'],
                ],
            ],
            [
                'industry_key' => 'field_services_maintenance',
                'industry_name' => 'Field Services & Maintenance',
                'icon_emoji' => '🔧',
                'description' => 'Trade businesses, maintenance companies, and field service operations.',
                'color_theme' => '#f59e0b',
                'recommended_modules' => ['field_service', 'assets', 'inventory', 'hr', 'finance', 'contracts', 'expenses'],
                'departments_template' => [
                    ['name' => 'Field Operations', 'code' => 'FIELD'],
                    ['name' => 'Scheduling & Dispatch', 'code' => 'DISPATCH'],
                    ['name' => 'Technical Support', 'code' => 'TECH'],
                    ['name' => 'Sales & Quoting', 'code' => 'SALES'],
                    ['name' => 'Finance & Administration', 'code' => 'FIN'],
                ],
                'chart_of_accounts_template' => [
                    ['code' => '1000', 'name' => 'Cash', 'type' => 'asset'],
                    ['code' => '1100', 'name' => 'Accounts Receivable', 'type' => 'asset'],
                    ['code' => '1200', 'name' => 'Parts & Supplies Inventory', 'type' => 'asset'],
                    ['code' => '1500', 'name' => 'Service Vehicles', 'type' => 'asset'],
                    ['code' => '1600', 'name' => 'Tools & Equipment', 'type' => 'asset'],
                    ['code' => '2000', 'name' => 'Accounts Payable', 'type' => 'liability'],
                    ['code' => '2100', 'name' => 'GST Payable', 'type' => 'liability'],
                    ['code' => '3000', 'name' => 'Owner Equity', 'type' => 'equity'],
                    ['code' => '4000', 'name' => 'Service Labour Revenue', 'type' => 'revenue'],
                    ['code' => '4100', 'name' => 'Parts & Materials Revenue', 'type' => 'revenue'],
                    ['code' => '4200', 'name' => 'Maintenance Contract Revenue', 'type' => 'revenue'],
                    ['code' => '5000', 'name' => 'Parts & Materials Cost', 'type' => 'expense'],
                    ['code' => '6000', 'name' => 'Technician Wages', 'type' => 'expense'],
                    ['code' => '6100', 'name' => 'Fuel & Vehicle Costs', 'type' => 'expense'],
                    ['code' => '6200', 'name' => 'Tools & Equipment', 'type' => 'expense'],
                    ['code' => '6300', 'name' => 'Insurance & Licences', 'type' => 'expense'],
                ],
            ],
        ];
    }
}
